# Generated by Django 5.1.2 on 2024-11-06 01:56

from django.db import migrations

def populate_priority(apps, schemaeditor):
    entries = {
        'high': 'A high priority issue',
        'medium': 'An issue of medium priority',
        'low': 'A low priority issue',
    }

    Priority = apps.get_model("issues", "Priority")  # where issues(the app its located in? ) and priority come from 
    for key, value in entries.items():
        priority = Priority(name=key, description=value)
        priority.save()





class Migration(migrations.Migration):

    dependencies = [
        ('issues', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(populate_priority)
    ]
