# Generated by Django 5.1.2 on 2024-11-06 02:07

from django.db import migrations



def populate_status(apps, schemaeditor):
    entries = {
        'to do': 'An issue for which work has not yet begun ',
        'in progress': 'An issue actively being worked on',
        'done': 'A completed issue',
        }
    Status = apps.get_model('issues', 'Status')
    for key, value in entries.items():
        status = Status(name=key, description=value)
        status.save()






class Migration(migrations.Migration):

    dependencies = [
        ('issues', '0002_auto_20241105_1756'),
    ]

    operations = [
        migrations.RunPython(populate_status),
    ]
